### ISSUE TITLE
Problem with the imager folder

### ISSUE THREAD

**Issue by aurianepez** [SNLC/ISI#2]
Hello,

I am currently trying to work with your code to show visual stimuli and do ISI image acquisition.

By following the steps described in the instructions, I was able to present visual stimuli. However, in order for the program to run, I have to remove the imager folder from the matlab path on the master computer; otherwise, I get the error message (1) below when trying to run the Stimulator.

Without the imager folder in the matlab path though, I get the error message (2) below when hitting "run" on the main window (as is kind of expected because of the missing libraries).

After several attempts of unsuccessful debugging, I thought it might be due to incompatibilities between different versions of Matlab; in the paper, it is mentioned that you used Matlab 2008, and we have Matlab 2017 on the master computer. Do you think this could be the cause? In that case, would you have a newer version of the code, compatible with newer matlab versions? Or any other suggestion on how we could proceed?

Thank you very much in advance for your help!

**Error Message (1)**
_Error: File: instrfindall.m Line: 1 Column: 25_
_The input character is not valid in MATLAB_
_statements or expressions._

_Error in configDisplayCom (line 11)_
_port =_
_instrfindall('RemoteHost',Mstate.stimulusIDP);_

_Error in Stimulator (line 9)_
_configDisplayCom    %stimulus computer_

**Error Message (2)**
_Undefined function or variable_
_'checkforOverwrite'._

_Error in MainWindow>runbutton_Callback (line 236)_
        _[Oflag dd] = checkforOverwrite;_

_Error in gui_mainfcn (line 95)_
        _feval(varargin{:});_

_Error in MainWindow (line 42)_
    _gui_mainfcn(gui_State, varargin{:});_

_Error in_
_matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)MainWindow('runbutton_Callback',hObject,eventdata,guidata(hObject))_ 
_Error while evaluating UIControl Callback._

**Comment by ajuavinett** [comment]
< from email discussion > 

**solution**: remove imager_mcf folder from path, keep the rest of the imager folder. this seems to fix the problem. 

i'll make these changes to the files released on github
